{:user
 {:repositories        [["central"  {:url "https://repo1.maven.org/maven2/" :snapshots false}]
                        ["clojars"  {:url "https://clojars.org/repo/"}]
                        ["nu-maven" {:url "s3p://nu-maven/releases/" :region "sa-east-1"}]]
  :plugin-repositories [["nu-maven" {:url "s3p://nu-maven/releases/"}]]
  :plugins             [[s3-wagon-private "1.3.3"]
                        [com.jakemccrary/lein-test-refresh "0.24.1"]
                        [cider/cider-nrepl "0.25.9"]
                        [nrepl/lein-nrepl "0.3.2"]
                        [refactor-nrepl "2.5.1"]]
  :injections          [(require 'nu)]
  :dependencies        [[cljdev "0.9.0"]
                        [nrepl "0.7.0"] ;; [nrepl "0.8.3"]
                        [com.bhauman/rebel-readline "0.1.4"]]
  :aliases             {"rebl" ["trampoline" "run" "-m" "rebel-readline.main"]}}}
