require('prelude')
require('plugins')

require('keymappings')
require('colorscheme')

require('treesitter')
require('lsp')

require('plugins.telescope')
require('plugins.compe')
require('plugins.galaxyline')
require('plugins.dashboard')
require('plugins.autopairs')

-- LSP
-- require('lsp.bash-ls')
-- require('lsp.clangd')
-- require('lsp.dart-ls')
-- require('lsp.docker-ls')
-- require('lsp.efm-general-ls')
-- require('lsp.graphql-ls')
-- require('lsp.go-ls')
-- require('lsp.json-ls')
-- require('lsp.js-ts-ls')
-- require('lsp.latex-ls')
require('lsp.lua')
require('lsp.clojure')
-- require('lsp.terraform-ls')
-- require('lsp.tailwindcss-ls')
-- require('lsp.vim-ls')
-- require('lsp.yaml-ls')
