require("prelude")
require("plugins")
require("common")

require("keymappings")
require("colorscheme")
require("lisp")

require("treesitter")
require("lsp")

require("plugins.telescope")
require("plugins.compe")
require("plugins.galaxyline")
require("plugins.autopairs")
require("plugins.lir")

-- LSP
require("lsp.clojure")
require("lsp.dart")
require("lsp.elixir")
require("lsp.scala")
require("lsp.latex")
require("lsp.lua")
require("lsp.go")
require("lsp.bash")
require("lsp.docker")
require("lsp.efm")
require("lsp.graphql")
require("lsp.typescript")
require("lsp.terraform")
require("lsp.install")
