require("prelude")
require("plugins")
require("common")

require("keymappings")
require("colorscheme")

require("treesitter")
require("lsp")

---- LSP
require("lsp.clojure")
require("lsp.dart")
require("lsp.elixir")
require("lsp.scala")
require("lsp.latex")
require("lsp.lua")
require("lsp.go")
require("lsp.bash")
require("lsp.docker")
require("lsp.efm")
require("lsp.graphql")
require("lsp.typescript")
require("lsp.terraform")
require("lsp.install")
